"""Markdown report generator for Lumiere."""

import os
from datetime import datetime
from ..core.models import Movie


def generate_markdown(
    movies: list[Movie],
    output_path: str,
    title: str = "Lumiere Movie Scan Report",
) -> str:
    """Generate a rich Markdown report with multi-source ratings."""
    today = datetime.now().strftime("%Y-%m-%d")

    with_rt = sum(1 for m in movies if m.rt.fetched)
    with_imdb = sum(1 for m in movies if m.imdb.fetched)
    avg_tmdb = sum(m.vote_average for m in movies) / len(movies) if movies else 0
    avg_imdb = sum((m.imdb.rating or 0) for m in movies if m.imdb.rating) / max(with_imdb, 1)
    avg_rt_critic = sum((m.rt.tomatometer or 0) for m in movies if m.rt.tomatometer) / max(
        sum(1 for m in movies if m.rt.tomatometer), 1
    )
    avg_rt_audience = sum((m.rt.popcornmeter or 0) for m in movies if m.rt.popcornmeter) / max(
        sum(1 for m in movies if m.rt.popcornmeter), 1
    )

    lines = [
        f"# {title}",
        "",
        f"*Generated by **Lumiere** — {today}*",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| **Total movies** | {len(movies)} |",
        f"| **TMDB avg rating** | {avg_tmdb:.1f}/10 |",
        f"| **IMDB avg rating** | {avg_imdb:.1f}/10 (across {with_imdb} movies) |",
        f"| **RT Tomatometer avg** | {avg_rt_critic:.0f}% (across {sum(1 for m in movies if m.rt.tomatometer)} movies) |",
        f"| **RT Popcornmeter avg** | {avg_rt_audience:.0f}% (across {sum(1 for m in movies if m.rt.popcornmeter)} movies) |",
        f"| **RT data available** | {with_rt}/{len(movies)} movies |",
        f"| **IMDB data available** | {with_imdb}/{len(movies)} movies |",
        "",
        "---",
        "",
        "## Movies",
        "",
    ]

    for i, movie in enumerate(movies, 1):
        tmdb_rating = movie.vote_average
        imdb_rating = movie.imdb.rating
        combined = movie.combined_score
        rt_t = movie.rt.tomatometer
        rt_p = movie.rt.popcornmeter
        lang = movie.original_language.upper() if movie.original_language else "?"

        lines.append(f"### {i}. {movie.title}")
        lines.append("")
        parts = [f"**TMDB:** {tmdb_rating}/10"]
        if imdb_rating is not None:
            parts.append(f"**IMDB:** {imdb_rating}/10")
        if rt_t is not None:
            parts.append(f"**RT Critics:** {rt_t}%")
        if rt_p is not None:
            parts.append(f"**RT Audience:** {rt_p}%")
        parts.append(f"**Combined:** {combined}/10")
        lines.append(" | ".join(parts))
        lines.append("")
        lines.append(f"Release: {movie.release_date or '?'}  |  Lang: {lang}  |  Genre: {', '.join(movie.genre_names) if movie.genre_names else '?'}  |  Votes: TMDB={movie.vote_count}" +
                     (f" IMDB={movie.imdb.vote_count}" if movie.imdb.vote_count else ""))
        if movie.runtime:
            lines.append(f"Runtime: {movie.runtime} min")
        lines.append("")
        if movie.tagline:
            lines.append(f'*"{movie.tagline}"*')
            lines.append("")
        overview_trunc = movie.overview[:300] + "..." if len(movie.overview) > 300 else movie.overview
        lines.append(f"> {overview_trunc}")
        lines.append("")
        links = []
        if movie.tmdb_url:
            links.append(f"[TMDB]({movie.tmdb_url})")
        if movie.imdb_url:
            links.append(f"[IMDB]({movie.imdb_url})")
        if movie.rt.url:
            links.append(f"[Rotten Tomatoes]({movie.rt.url})")
        if links:
            lines.append(" | ".join(links))
            lines.append("")
        lines.append("---")
        lines.append("")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    content = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    return output_path
